-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Apr 18, 2026 at 02:38 AM
-- Server version: 8.0.30
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `duan1`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `price` decimal(25,2) DEFAULT NULL,
  `description` text,
  `content` text,
  `type` varchar(10) NOT NULL,
  `status` enum('active','inactive') DEFAULT 'active',
  `category_id` int NOT NULL,
  `view` int DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `image`, `price`, `description`, `content`, `type`, `status`, `category_id`, `view`, `created_at`) VALUES
(18, 'Áo sơ mi 001', 'Assets/Admin/Uploads/1776478634_69e2e9aa035ae.png', '100000.00', '1Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Quần', 'active', 1, 18, '2026-04-17 06:23:41'),
(19, 'Áo sơ mi 002', 'Assets/Admin/Uploads/1776478714_69e2e9fa5bd3c.png', '350000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Áo', 'active', 1, 13, '2026-04-17 06:42:39'),
(20, 'Áo sơ mi 003', 'Assets/Admin/Uploads/1776478741_69e2ea15e2a51.jpg', '200000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', '1Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Áo', 'active', 1, 1, '2026-04-17 06:47:18'),
(21, 'Áo jacket 001', 'Assets/Admin/Uploads/1776478815_69e2ea5f92156.jpg', '200000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Áo', 'active', 2, 0, '2026-04-18 02:20:15'),
(22, 'Áo jacket 002', 'Assets/Admin/Uploads/1776478849_69e2ea816dc7e.jpg', '400000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Áo', 'active', 2, 0, '2026-04-18 02:20:49'),
(23, 'Áo blazer 001', 'Assets/Admin/Uploads/1776478890_69e2eaaa4729e.png', '250000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Áo', 'active', 3, 0, '2026-04-18 02:21:30'),
(24, 'Áo blazer 0012', 'Assets/Admin/Uploads/1776478926_69e2eace13019.png', '400000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Áo', 'active', 3, 0, '2026-04-18 02:22:06'),
(25, 'Áo blazer 003', 'Assets/Admin/Uploads/1776478969_69e2eaf9324e4.png', '200000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Áo', 'active', 3, 0, '2026-04-18 02:22:49'),
(26, 'Quần tây 001', 'Assets/Admin/Uploads/1776479003_69e2eb1ba4a21.jpg', '200000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Quần', 'active', 4, 0, '2026-04-18 02:23:23'),
(27, 'Quần tây 002', 'Assets/Admin/Uploads/1776479035_69e2eb3b0f31a.png', '500000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Quần', 'active', 4, 0, '2026-04-18 02:23:55'),
(28, 'Quần short 001', 'Assets/Admin/Uploads/1776479067_69e2eb5b6bee7.jpg', '4000000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Quần', 'active', 5, 0, '2026-04-18 02:24:27'),
(29, 'Quần short 002', 'Assets/Admin/Uploads/1776479099_69e2eb7b1df4e.jpg', '300000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Quần', 'active', 5, 0, '2026-04-18 02:24:59'),
(30, 'Quần short 003', 'Assets/Admin/Uploads/1776479151_69e2ebaf45abe.jpg', '250000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Quần', 'active', 5, 0, '2026-04-18 02:25:51'),
(31, 'Quần kaki 001', 'Assets/Admin/Uploads/1776479187_69e2ebd30c8f7.jpg', '200000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Quần', 'active', 7, 0, '2026-04-18 02:26:27'),
(32, 'Quần jeans 001', 'Assets/Admin/Uploads/1776479229_69e2ebfd0203a.png', '250000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Quần', 'active', 7, 0, '2026-04-18 02:27:09'),
(33, 'Quần jeans 002', 'Assets/Admin/Uploads/1776479265_69e2ec2192e2a.jpg', '600000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Quần', 'active', 7, 0, '2026-04-18 02:27:45'),
(34, 'Tất 001', 'Assets/Admin/Uploads/1776479291_69e2ec3b25716.jpg', '35000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Phụ Kiện', 'active', 8, 0, '2026-04-18 02:28:11'),
(35, 'Dây lưng 001', 'Assets/Admin/Uploads/1776479318_69e2ec5637bc7.png', '250000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Phụ Kiện', 'active', 9, 0, '2026-04-18 02:28:38'),
(36, 'Dây lưng 002', 'Assets/Admin/Uploads/1776479370_69e2ec8a85dfb.png', '200000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Phụ Kiện', 'active', 9, 0, '2026-04-18 02:29:30'),
(37, 'Ví da 001', 'Assets/Admin/Uploads/1776479406_69e2ecaec5e45.jpg', '400000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Phụ Kiện', 'active', 10, 0, '2026-04-18 02:30:06'),
(38, 'Cà vạt 001', 'Assets/Admin/Uploads/1776479572_69e2ed54346f4.jpg', '120000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Phụ Kiện', 'active', 11, 0, '2026-04-18 02:32:52'),
(39, 'giày 001', 'Assets/Admin/Uploads/1776479632_69e2ed90084d5.jpg', '250000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Phụ Kiện', 'active', 12, 0, '2026-04-18 02:33:52'),
(40, 'Giày 002', 'Assets/Admin/Uploads/1776479684_69e2edc4aa61f.jpg', '300000.00', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Đặc điểm chi tiết của áo sơ mi:\r\nCấu trúc: Gồm cổ áo (cổ bẻ, button-down), thân áo, tay áo và hàng nút cài phía trước.\r\nChất liệu: Thường dùng vải kate mềm mại, vải cotton thoáng mát, hoặc linen cho mùa hè.\r\nPhom dáng:\r\nClassic Fit (Cổ điển): Rộng rãi, thoải mái, phù hợp nhiều dáng người.\r\nSlim Fit (Ôm sát): Tôn dáng, trẻ trung.\r\nRegular Fit (Vừa vặn): Thoải mái, phù hợp đi làm.\r\n', 'Phụ Kiện', 'active', 12, 0, '2026-04-18 02:34:44');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD KEY `category_id` (`category_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `products_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
